name: PhantomSMP
version: @version@
author: Simon Chuu
description: Advanced phantom mechanics especially for SMP servers
main: com.simonorj.mc.phantomsmp.PhantomSMP
website: https://github.com/SimonOrJ/PhantomSMP
api-version: 1.14

permissions:
  phantomsmp.disallowspawn:
    description: Don't let phantom spawn on the player.
    default: false
  phantomsmp.ignore:
    description: >
      Don't let phantoms target the player.
      This will ignore `remove-targeting-rested` configuration option for the
      player and keep the phantom flying around as if nothing happened.
    default: false
